//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SeatingMvc.Components.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SeatingDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SeatingDbEntities object using the connection string found in the 'SeatingDbEntities' section of the application configuration file.
        /// </summary>
        public SeatingDbEntities() : base("name=SeatingDbEntities", "SeatingDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SeatingDbEntities object.
        /// </summary>
        public SeatingDbEntities(string connectionString) : base(connectionString, "SeatingDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SeatingDbEntities object.
        /// </summary>
        public SeatingDbEntities(EntityConnection connection) : base(connection, "SeatingDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> People
        {
            get
            {
                if ((_People == null))
                {
                    _People = base.CreateObjectSet<Person>("People");
                }
                return _People;
            }
        }
        private ObjectSet<Person> _People;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Table> Tables
        {
            get
            {
                if ((_Tables == null))
                {
                    _Tables = base.CreateObjectSet<Table>("Tables");
                }
                return _Tables;
            }
        }
        private ObjectSet<Table> _Tables;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTables(Table table)
        {
            base.AddObject("Tables", table);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeatingDBModel", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="personId">Initial value of the PersonId property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastname">Initial value of the Lastname property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        /// <param name="age">Initial value of the Age property.</param>
        public static Person CreatePerson(global::System.Int64 personId, global::System.String firstName, global::System.String lastname, global::System.String gender, global::System.Int32 age)
        {
            Person person = new Person();
            person.PersonId = personId;
            person.FirstName = firstName;
            person.Lastname = lastname;
            person.Gender = gender;
            person.Age = age;
            return person;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PersonId
        {
            get
            {
                return _PersonId;
            }
            set
            {
                if (_PersonId != value)
                {
                    OnPersonIdChanging(value);
                    ReportPropertyChanging("PersonId");
                    _PersonId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PersonId");
                    OnPersonIdChanged();
                }
            }
        }
        private global::System.Int64 _PersonId;
        partial void OnPersonIdChanging(global::System.Int64 value);
        partial void OnPersonIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lastname
        {
            get
            {
                return _Lastname;
            }
            set
            {
                OnLastnameChanging(value);
                ReportPropertyChanging("Lastname");
                _Lastname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lastname");
                OnLastnameChanged();
            }
        }
        private global::System.String _Lastname;
        partial void OnLastnameChanging(global::System.String value);
        partial void OnLastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.Int32 _Age;
        partial void OnAgeChanging(global::System.Int32 value);
        partial void OnAgeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeatingDBModel", Name="Table")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Table : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Table object.
        /// </summary>
        /// <param name="tableId">Initial value of the TableId property.</param>
        /// <param name="tableNum">Initial value of the TableNum property.</param>
        /// <param name="numberOfSeats">Initial value of the NumberOfSeats property.</param>
        public static Table CreateTable(global::System.Int64 tableId, global::System.Int32 tableNum, global::System.Int32 numberOfSeats)
        {
            Table table = new Table();
            table.TableId = tableId;
            table.TableNum = tableNum;
            table.NumberOfSeats = numberOfSeats;
            return table;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TableId
        {
            get
            {
                return _TableId;
            }
            set
            {
                if (_TableId != value)
                {
                    OnTableIdChanging(value);
                    ReportPropertyChanging("TableId");
                    _TableId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TableId");
                    OnTableIdChanged();
                }
            }
        }
        private global::System.Int64 _TableId;
        partial void OnTableIdChanging(global::System.Int64 value);
        partial void OnTableIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TableNum
        {
            get
            {
                return _TableNum;
            }
            set
            {
                OnTableNumChanging(value);
                ReportPropertyChanging("TableNum");
                _TableNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TableNum");
                OnTableNumChanged();
            }
        }
        private global::System.Int32 _TableNum;
        partial void OnTableNumChanging(global::System.Int32 value);
        partial void OnTableNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumberOfSeats
        {
            get
            {
                return _NumberOfSeats;
            }
            set
            {
                OnNumberOfSeatsChanging(value);
                ReportPropertyChanging("NumberOfSeats");
                _NumberOfSeats = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumberOfSeats");
                OnNumberOfSeatsChanged();
            }
        }
        private global::System.Int32 _NumberOfSeats;
        partial void OnNumberOfSeatsChanging(global::System.Int32 value);
        partial void OnNumberOfSeatsChanged();

        #endregion

    
    }

    #endregion

    
}
